### ISSUE TITLE
parse in as inches

### ISSUE THREAD

**Issue by liarig** [nielstron/quantulum3#128]
**Describe the bug**
An inch wasn't parsed in this example
```python
from quantulum3 import parser
>>> parser.parse('length is 1 in')
[Quantity(1, "Unit(name="dimensionless", entity=Entity("dimensionless"), uri=Dimensionless_quantity)")]```

**Comment by nielstron** [comment]
Thanks for the issue, this is due to the heuristic that "in" is the proposition instead of inches in most cases (https://github.com/nielstron/quantulum3/blob/41fa4fbec367aac97f9058614dc629e9b52d5e15/quantulum3/_lang/en_US/parser.py#L187)

Obviously this does not make sense if the in is appearing at the end of a sentence or a sentence divider. A corresponding regex should be added.
